### ISSUE TITLE
How legit is this repository, is it suported by vmware?

### ISSUE THREAD

**Issue by cadesalaberry** [vmwareairwatchsdk/vmware-wsone-sdk-cordova#3]
I assume this package uses the swift package under the same organisation (https://github.com/vmwareairwatchsdk)

https://github.com/vmwareairwatchsdk/iOS-WorkspaceONE-SDK/blob/master/Package.swift

I did not find any obvious link between https://github.com/vmware/ and this Github organisation.

@ananyajoshi @akalghatgi @Maddy79 could you care to explain your relation with VMWare? Are you part of the company? Why are you not using the [vmware](https://github.com/vmware/) github organisation to publish your code?

**Comment by Maddy79** [comment]
@cadesalaberry , Yes this is part of the official VMware Workspace ONE SDK project.
